"""empty message

Revision ID: 106dba27fbf0
Revises: e2b716262217
Create Date: 2017-08-21 15:00:29.072651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106dba27fbf0'
down_revision = 'e2b716262217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
