"""empty message

Revision ID: 408c4fd1ca16
Revises: 106dba27fbf0
Create Date: 2017-08-27 13:25:54.555013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408c4fd1ca16'
down_revision = '106dba27fbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world')
    # ### end Alembic commands ###
